### ISSUE TITLE
Implement hook_config_info()

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/maildisguise#3]
By implementing [hook_config_info()](https://api.backdropcms.org/api/backdrop/core%21modules%21config%21config.api.php/function/hook_config_info/1), not only will that allow exporting your config via the UI, but it will mean config is automatically deleted on uninstall (so no need to do this manually in the `.install` file).

**Comment by ghost** [comment]
Oh, and it seems you need to provide a default config file too...

**Comment by ghost** [comment]
The [PR](https://github.com/backdrop-contrib/maildisguise/pull/4) implements `hook_config_info()`, removes the unnecessary `hook_uninstall()` implementation, and adds a default config file.

It also changes the code in `maildisguise_install()` from:
```php
$config = config('maildisguise.settings');
$config->set('css_class', $css_class);
$config->save();
```
to the simpler:
```php
config_set('maildisguise.settings', 'css_class', $css_class);
```
(the former is good when you're doing a few different things with config (e.g. reading different values, setting different values, etc.) - it prevents having to open the same config file multiple times. But the latter is easier when you're only doing one thing with config, like here.

Hope that helps!

**Comment by indigoxela** [comment]
@BWPanda yeah, you're perfectly right. I didn't merge your PR directly because of the directory name typo (contrib vs. config).
