### ISSUE TITLE
A few coding optimisation possibilities...?

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/maildisguise#7]
I'm just reading through the code for this module, because I'm interested to know what it does and how it works, and I noticed a few things I thought I'd point out as possible optimisations. But feel free to ignore any/all of these things.

- https://github.com/backdrop-contrib/maildisguise/blob/2e583032173cb9f35dd5d1be55efbdd7d45f5d54/maildisguise.module#L77-L79 Does the `#maxlength` not account for this already?

- https://github.com/backdrop-contrib/maildisguise/blob/2e583032173cb9f35dd5d1be55efbdd7d45f5d54/maildisguise.module#L80-L82 Can you not just run the user's value through `backdrop_clean_css_identifier()`, then compare the output with the user's value to see if it's changed? If it has, throw the error, if not, you're all good. Something like:
  ```
  if ($css_class != backdrop_clean_css_identifier($css_class)) {
    form_set_error('css_class', t('The input contains characters not allowed in CSS classes.'));
  }
  ```

**Comment by indigoxela** [comment]
Hey, don't blame me for my code from a year ago... :laughing: 

Many thanks for your hints, they're appreciated. Will have a look ASAP.
